### ISSUE TITLE
Why not contribute this to the Dash user contributed docsets?

### ISSUE THREAD

**Issue by dsifford** [vaz-ar/Autohotkey.docset#2]
Hi there,

Docset looks good. Have you considered [contributing to Dash directly](https://github.com/Kapeli/Dash-User-Contributions) so that people can download this using the native app? 

If you already do this, I'm not seeing it anywhere listed in the User Contributed section.

Thanks

**Comment by dufferzafar** [comment]
:+1:

**Comment by vaz-ar** [comment]
Hello,
Yes I have considered it some time ago, but I have to admit that I was a bit lost regarding how to do it.
I'll check again and see what I can do.
Thanks for the suggestion !

**Comment by vaz-ar** [comment]
There is another problem: I initially made this docset for Zeal, I do not use Dash (I am on Windows/Linux) so I don't know if I'll be able to test this.

**Comment by dsifford** [comment]
@vaz-ar Thanks! I'm a Zeal user as well, but I recently came across [Velocity](https://velocity.silverlakesoftware.com/) for Windows which seems to be a bit more feature-rich than zeal. 

I'd be happy to help in the process if you'd like.... I'm not sure of the specifics, but I can read them over, make whatever changes need to be made, and then submit a PR if you'd like.

**Comment by vaz-ar** [comment]
@dsifford If you want to give it a shot please do, I won't have time to look into it this week.

**Comment by dsifford** [comment]
@vaz-ar Just got around to looking through the requirements. 

The only change that needs to be made before this docset is ready to be submitted is you need to add the following key/value pair to the `info.plist` file...

``` xml
<key>DashDocSetFallbackURL</key>
<string>https://autohotkey.com/docs/</string>
```

Otherwise, this is good to go as-is. All that you'd have to do to get this tracked by Dash is follow the few steps [outlined here](https://github.com/Kapeli/Dash-User-Contributions#contribute-a-new-docset). Thanks again.

**Comment by vaz-ar** [comment]
Ok thanks! I'll look into it as soon as I can.

**Comment by vaz-ar** [comment]
Sorry for the delay, I haven't forgotten about it, just didn't have a lot of spare time. I'll be doing this in the next couple of weeks.

**Comment by vaz-ar** [comment]
So I finally got around to do it, I just submitted the pull request, I'll let you know when it is validated.

**Comment by vaz-ar** [comment]
Done!
